// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using CricketData;
//
//    var leagueData = LeagueData.FromJson(jsonString);

namespace ignt.sports.cricket.network
{
    [System.Serializable]
    public class LeagueData
    {
        public League[] Leagues;
    }

    public class League
    {
        public string LeagueId;

        public string LeagueName;

        public int PrizePool;

        public int EntryFee;

        public string AllowedUserTeamSlots;

        public int TotalTeamsJoined;

        public string MatchId;

        public string TeamAFlagImageUrl;

        public string TeamBFlagImageUrl;

        public string TeamACaptainImageUrl;

        public string TeamBCaptainImageUrl;
    }
    

}

